// app/api/odi/queryMap.js

export const ODI_QUERY_MAP = {
  CM_INTERVAL_TREND: {
    sql: `SELECT MAX(READ_DATE) FROM CM_INTERVAL_TREND`,
    type: "DATE",
  },
  CM_INTERVAL_SUM: {
    sql: `SELECT MAX(CRE_DTTM) FROM CM_INTERVAL_SUM`,
    type: "DATE",
  },
  CM_INTERVAL_COUNT: {
    sql: `SELECT MAX(READ_DATE) FROM CM_INTERVAL_COUNT`,
    type: "DATE",
  },
  CM_DAILY_MISSING_SUM: {
    sql: `SELECT MAX(CRE_DTTM) FROM CM_DAILY_MISSING_SUM`,
    type: "DATE",
  },
  CM_PEAK_OFFPEAK: {
    sql: `SELECT MAX(READ_DATE) FROM CM_PEAK_OFFPEAK`,
    type: "DATE",
  },
  CM_ZERO_CONSUMPTION: {
    sql: `SELECT MAX(CM_ENDDT) FROM CM_ZERO_CONSUMPTION`,
    type: "DATE",
  },
  HOURLY_CONSUMPTION_DETAILS: {
    sql: `SELECT * FROM HOURLY_CONSUMPTION_DETAILS where trunc(HOUR_TIMESTAMP)=trunc(sysdate)-1;`,
    type: "DATE",
  },
  MONTHLY_CONSUMPTION_IMPORT: {
    sql: `SELECT * FROM MONTHLY_CONSUMPTION_IMPORT where trunc(MONTH) > sysdate-1;`,
    type: "DATE",
  },
  MONTHLY_CONSUMPTION_VARIATION_2: {
    sql: `SELECT * FROM MONTHLY_CONSUMPTION_VARIATION_2 where trunc(MONTH) > sysdate-1; `,
    type: "DATE",
  },
  CM_REPORT_DN_ANALYSIS: {
    sql: `SELECT MAX(INTERVAL_DATE) FROM CM_REPORT_DN_ANALYSIS`,
    type: "DATE",
  },
  CM_REPORT_VA_ANALYSIS: {
    sql: `SELECT MAX(INTERVAL_DATE) FROM CM_REPORT_VA_ANALYSIS`,
    type: "DATE",
  },
  CM_NET_CONSUMPTION_DAILY: {
    sql: `SELECT * FROM CM_NET_CONSUMPTION_DAILY where TRUNC(MONTH) > sysdate-1; `,
    type: "DATE",
  },
  METER_INSTALLATION_DAILY: {
    sql: `SELECT MAX(REPORT_DATE) FROM METER_INSTALLATION_DAILY`,
    type: "DATE",
  },
  MONTHLY_CONS_VARIATION: {
    sql: `SELECT MAX(LOADSTAMP) FROM MONTHLY_CONS_VARIATION`,
    type: "DATE",
  },
  CM_CRITICAL_EVENTS_DAILY: {
    sql: `SELECT MAX(RPT_DATE) FROM CM_CRITICAL_EVENTS_DAILY`,
    type: "DATE",
  },
  CM_NON_CRITICAL_EVENTS_DAILY: {
    sql: `SELECT MAX(RPT_DATE) FROM CM_NON_CRITICAL_EVENTS_DAILY`,
    type: "DATE",
  },
  CM_OUTAGE_EVENTS_DAILY: {
    sql: `SELECT MAX(RPT_DATE) FROM CM_OUTAGE_EVENTS_DAILY`,
    type: "DATE",
  },
  S1_MDM_METER_INSTALLED: {
    sql: `SELECT COUNT (*) FROM S1_MDM_METER_INSTALLED;`,
    type: "COUNT",
  },
  MV1_RCDC_DC_SUMMARY: {
    sql: `SELECT MAX(START_DATE) FROM MV1_RCDC_DC_SUMMARY`,
    type: "DATE",
  },
  MV1_CONSUMER_MASTER: {
    sql: `SELECT MAX(PROCESSED_DTTM) FROM MV1_CONSUMER_MASTER`,
    type: "DATE",
  },
  B1_FDR_DLY_CONS: {
    sql: `SELECT MAX(FDR_DATE) FROM B1_FDR_DLY_CONS`,
    type: "DATE",
  },
  B1_DT_DAILY_CONSUMPTION: {
    sql: `SELECT MAX(DT_DATE) FROM B1_DT_DAILY_CONSUMPTION`,
    type: "DATE",
  },
  MV1_SLA_RC_DC: {
    sql: `SELECT MAX(ACTIVITY_DATE) FROM MV1_SLA_RC_DC`,
    type: "DATE",
  },
  CM_DAILY_SLA_MDM: {
    sql: `SELECT MAX(CRE_DTTM) FROM CM_DAILY_SLA_MDM`,
    type: "DATE",
  },
  CM_MONTHLY_SLA_MDM: {
    sql: `SELECT MAX(CRE_DTTM) FROM CM_MONTHLY_SLA_MDM`,
    type: "DATE",
  },
  CM_INTERVAL_SLA_MDM: {
    sql: `SELECT MAX(CRE_DTTM) FROM CM_INTERVAL_SLA_MDM`,
    type: "DATE",
  },
  SLA_MONTHLY_SLA_MONITORING_MV: {
    sql: `SELECT MAX(MONTH) FROM SLA_MONTHLY_SLA_MONITORING_MV`,
    type: "DATE",
  },
  SLA_MV_DAY_PARAM: {
    sql: `SELECT MAX(PARAM_DATE) FROM SLA_MV_DAY_PARAM`,
    type: "DATE",
  },
  RCDCDETAILS: {
    sql: `SELECT MAX(SOARECEIVEDTIME) FROM RCDCDETAILS`,
    type: "DATE",
  },
  RCDCDETAILS_DROP: {
    sql: `SELECT MAX(SOARECEIVEDTIME) FROM RCDCDETAILS`,
    type: "DATE",
  },
  INTERVAL_SLA_MONITORING: {
    sql: `SELECT MAX(READ_DATE) FROM INTERVAL_SLA_MONITORING`,
    type: "DATE",
  },
  PREPAIDRECHARGE_TRANSACTIONS: {
    sql: `SELECT MAX(PAYMENT_DTTM) FROM CISADM.PREPAIDRECHARGE_TRANSACTIONS`,
    type: "DATE",
  },
};
