import { NextResponse } from "next/server";
import { getOdiDB } from "../../../lib/db-odi";

/*
  ONE API
  - Executes ONE query per request
  - Supports parallel requests
  - Safe & scalable
*/

const QUERY_MAP = {
  CM_INTERVAL_TREND: `SELECT MAX(READ_DATE) FROM CM_INTERVAL_TREND`,
  CM_INTERVAL_SUM: `SELECT MAX(CRE_DTTM) FROM CM_INTERVAL_SUM`,
  CM_INTERVAL_COUNT: `SELECT MAX(READ_DATE) FROM CM_INTERVAL_COUNT`,
  CM_DAILY_MISSING_SUM: `SELECT MAX(CRE_DTTM) FROM CM_DAILY_MISSING_SUM`,
  CM_PEAK_OFFPEAK: `SELECT MAX(READ_DATE) FROM CM_PEAK_OFFPEAK`,
  CM_ZERO_CONSUMPTION: `SELECT MAX(CM_ENDDT) FROM CM_ZERO_CONSUMPTION`,

  HOURLY_CONSUMPTION_DETAILS: `
    SELECT MAX(HOUR_TIMESTAMP)
    FROM HOURLY_CONSUMPTION_DETAILS
    WHERE TRUNC(HOUR_TIMESTAMP) > SYSDATE - 1
  `,

  MONTHLY_CONSUMPTION_IMPORT: `
    SELECT MAX(MONTH)
    FROM MONTHLY_CONSUMPTION_IMPORT
    WHERE TRUNC(MONTH) > SYSDATE - 1
  `,

  MONTHLY_CONSUMPTION_VARIATION_2: `
    SELECT MAX(MONTH)
    FROM MONTHLY_CONSUMPTION_VARIATION_2
    WHERE TRUNC(MONTH) > SYSDATE - 1
  `,

  CM_REPORT_DN_ANALYSIS: `SELECT MAX(INTERVAL_DATE) FROM CM_REPORT_DN_ANALYSIS`,
  CM_REPORT_VA_ANALYSIS: `SELECT MAX(INTERVAL_DATE) FROM CM_REPORT_VA_ANALYSIS`,

  CM_NET_CONSUMPTION_DAILY: `
    SELECT MAX(MONTH)
    FROM CM_NET_CONSUMPTION_DAILY
    WHERE TRUNC(MONTH) > SYSDATE - 1
  `,

  METER_INSTALLATION_DAILY: `SELECT MAX(REPORT_DATE) FROM METER_INSTALLATION_DAILY`,
  MONTHLY_CONS_VARIATION: `SELECT MAX(LOADSTAMP) FROM MONTHLY_CONS_VARIATION`,

  CM_CRITICAL_EVENTS_DAILY: `SELECT MAX(RPT_DATE) FROM CM_CRITICAL_EVENTS_DAILY`,
  CM_NON_CRITICAL_EVENTS_DAILY: `SELECT MAX(RPT_DATE) FROM CM_NON_CRITICAL_EVENTS_DAILY`,
  CM_OUTAGE_EVENTS_DAILY: `SELECT MAX(RPT_DATE) FROM CM_OUTAGE_EVENTS_DAILY`,

  S1_MDM_METER_INSTALLED: `SELECT COUNT(*) FROM S1_MDM_METER_INSTALLED`,

  MV1_RCDC_DC_SUMMARY: `SELECT MAX(START_DATE) FROM MV1_RCDC_DC_SUMMARY`,
  MV1_CONSUMER_MASTER: `SELECT MAX(PROCESSED_DTTM) FROM MV1_CONSUMER_MASTER`,

  B1_FDR_DLY_CONS: `SELECT MAX(FDR_DATE) FROM B1_FDR_DLY_CONS`,
  B1_DT_DAILY_CONSUMPTION: `SELECT MAX(DT_DATE) FROM B1_DT_DAILY_CONSUMPTION`,

  MV1_SLA_RC_DC: `SELECT MAX(ACTIVITY_DATE) FROM MV1_SLA_RC_DC`,
  CM_DAILY_SLA_MDM: `SELECT MAX(CRE_DTTM) FROM CM_DAILY_SLA_MDM`,
  CM_MONTHLY_SLA_MDM: `SELECT MAX(CRE_DTTM) FROM CM_MONTHLY_SLA_MDM`,
  CM_INTERVAL_SLA_MDM: `SELECT MAX(CRE_DTTM) FROM CM_INTERVAL_SLA_MDM`,

  SLA_MONTHLY_SLA_MONITORING_MV: `
    SELECT MAX(MONTH)
    FROM ODI_SCHEMA_TARGET.SLA_MONTHLY_SLA_MONITORING_MV
  `,

  SLA_MV_DAY_PARAM: `SELECT MAX(CRE_DTTM) FROM SLA_MV_DAY_PARAM`,
  RCDCDETAILS: `SELECT MAX(SOARECEIVEDTIME) FROM RCDCDETAILS`,
  INTERVAL_SLA_MONITORING: `SELECT MAX(READ_DATE) FROM INTERVAL_SLA_MONITORING`,

  PREPAIDRECHARGE_TRANSACTIONS: `
    SELECT MAX(PAYMENT_DTTM)
    FROM CISADM.PREPAIDRECHARGE_TRANSACTIONS
  `,
};

export async function POST(req) {
  let conn;

  try {
    const { jobKey } = await req.json();

    if (!jobKey || !QUERY_MAP[jobKey]) {
      return NextResponse.json(
        { error: "Invalid or missing jobKey" },
        { status: 400 }
      );
    }

    conn = await getOdiDB();

    const result = await conn.execute(QUERY_MAP[jobKey]);

    const lastUpdated = result.rows?.[0]?.[0] || null;

    return NextResponse.json({
      lastUpdated,
      tableStatus: lastUpdated ? "UPDATED" : "NOT UPDATED",
    });

  } catch (err) {
    console.error("ODI VALIDATE API ERROR:", err);
    return NextResponse.json(
      { error: err.message },
      { status: 500 }
    );
  } finally {
    if (conn) {
      try {
        await conn.close();
      } catch (e) {
        console.error("ODI DB CLOSE ERROR:", e);
      }
    }
  }
}
